server:
  port: 10099
spring:
  application:
    name: blog-service
  datasource:
    url: jdbc:mysql://101.132.194.179:3306/wechat?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: huajun123
    driver-class-name: com.mysql.cj.jdbc.Driver
eureka:
  client:
    service-url:
      defaultZone: http://localhost:10086/eureka
    register-with-eureka: true
    fetch-registry: true
    registry-fetch-interval-seconds: 10
  instance:
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10