server:
  port: 10099
spring:
  application:
    name: blog-service
  datasource:
    url: jdbc:mysql://101.132.194.179:3306/wechat?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: huajun123
    driver-class-name: com.mysql.cj.jdbc.Driver
  rabbitmq:
    host: 123.56.134.245
    username: hujkc123
    password: huajun123
    virtual-host: /huajun
    template:
      exchange: es.blog.exchange
    publisher-confirms: true
  profiles:
    active: ${profile}
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
