eureka:
  instance:
    ip-address: "${host}"
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: ${registry}/eureka
image:
  docker-path: /huanghan
  path: /home/hujkc123/images
  link: http://images.huajun.link

