server:
  port: 10034
eureka:
  client:
    service-url:
      defaultZone: http://localhost:10086/eureka
    registry-fetch-interval-seconds: 10
    fetch-registry: true
    register-with-eureka: true
  instance:
    lease-expiration-duration-in-seconds: 10
    lease-renewal-interval-in-seconds: 5
feign:
  client:
    config:
      item-service:
        connectTimeout: 10000
        readTimeout: 10000
spring:
  application:
    name: edit-service
  profiles:
    active: ${profile}
  rabbitmq:
    host: 123.56.134.245
    username: hujkc123
    password: huajun123
    virtual-host: /huajun