server:
  port: 10022
spring:
  application:
    name: upload-service
  resources:
    static-locations: file:///home/hujkc123/images
  servlet:
    multipart:
      enabled: true
      max-file-size: 200MB
      max-request-size: 200MB