server:
  port: 10002
spring:
  application:
    name: item-service
  datasource:
    username: root
    password: huajun123
    url: jdbc:mysql://101.132.194.179:3306/wechat?serverTimezone=UTC&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      minimum-idle: 3
      maximum-pool-size: 10
      max-lifetime: 30000
  rabbitmq:
    host: 123.56.134.245
    username: hujkc123
    password: huajun123
    virtual-host: /huajun
    template:
      exchange: item.create.exchange
    publisher-confirms: true
  profiles:
    active: ${profile}
eureka:
  client:
    register-with-eureka: true
