server:
  port: 8088
spring:
  application:
    name: search-service
  data:
    elasticsearch:
      cluster-name: docker-cluster
      cluster-nodes: 123.56.134.245:9300
  jackson:
    default-property-inclusion: non_null
  rabbitmq:
    host: 123.56.134.245
    username: hujkc123
    password: huajun123
    virtual-host: /huajun
#    template:
#      exchange: huajun.elasticsearch.exchanger
#    publisher-confirms: true
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
    fetch-registry: true
    registry-fetch-interval-seconds: 10
  instance:
    lease-expiration-duration-in-seconds: 10
    lease-renewal-interval-in-seconds: 5
feign:
  client:
    config:
      item-service:
        connectTimeout: 10000
        readTimeout: 10000