server:
  port: 10010
spring:
  application:
    name: wechat-zuul
  profiles:
    active: ${profile}
  servlet:
    multipart:
      max-file-size: -1
      max-request-size: -1
      enabled: true
zuul:
  prefix: /api
  routes:
    item-service: /item/**
    search-service: /search/**
    edit-service: /edit/**
    pulldata-service: /pull/**
    blog-service: /blog/**
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
ribbon:
  ReadTimeout: 10000
  ConnectTimeout: 10000
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 40000
