server:
  port: 3340
eureka:
  client:
    service-url:
      defaultZone: http://localhost:10086/eureka
  instance:
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10
spring:
  application:
    name: pulldata-service
  redis:
    host: 127.0.0.1